export default [
  {
    id: 1,
    img: require('../assets/slide.png'),
    title: 'Offer 1 ',
    description: 'The future of health is on your wrist',
    price: '$399',
  },
  {
    id: 2,
    // img: require('../assets/airpod.jpeg'),
    img: require('../assets/slide.png'),
    // title: 'AirPods Pro',
    title: 'Offer 2 ',
    description: 'Active noise cancellation for immersive sound',
    price: '$249',
  },
  {
    id: 3,
    // img: require('../assets/airpodmax.jpeg'),
    img: require('../assets/slide.png'),
    title: 'Offer 3 ',
    description: 'Effortless AirPods experience',
    price: '$549',
  },
  {
    id: 4,
    // img: require('../assets/charger.png'),
    img: require('../assets/slide.png'),
    // title: 'Charger',
    title: 'Offer 4 ',
    description: "It's not magic, it's just science",
    price: '$49',
  },
  {
    id: 5,
    // img: require('../assets/lock.jpeg'),
    img: require('../assets/slide.png'),
    // title: 'Smart Lock',
    title: 'Offer 5 ',
    description: 'Unlock your door with your phone',
    price: '$199',
  },
];
